export { default as Home } from './Home'
export { default as Contact } from './Contact'
export { default as Offices } from './Offices'
export { default as OurTeam } from './OurTeam'
export { default as About } from './About' 